title = "Bogdanworks"
baseURL = "https://www.bogdanworks.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
# themesDir = "../.."
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "BogdanWorks"
    weight = 1
    contentDir = "content"
 # [languages.fr]
 #   title = "Mon blogue"
 #   weight = 2
 #   contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/icon_BogdanWorks.ico"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/bogdanworks"
  instagram = "https://instagram.com/bogdanworks"
  youtube = ""
  github = "https://github.com/bogdanworks"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/matthew-bogdan-pmp®-csm®-b7729b33/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/desk.jpg"
  recent_posts_number = 6